// <auto-generated />
using System;
using DmResinas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DmResinas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231205133527_criar-banco")]
    partial class criarbanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DmResinas.Models.Categoria", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Banner")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("CategoriaPaiId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Filtrar")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Banner = true,
                            Filtrar = true,
                            Foto = "images/categorias/1.png",
                            Nome = "Folha-de-Ouro"
                        },
                        new
                        {
                            Id = (byte)2,
                            Banner = true,
                            Filtrar = true,
                            Foto = "images/categorias/2.png",
                            Nome = "Flores"
                        },
                        new
                        {
                            Id = (byte)3,
                            Banner = true,
                            Filtrar = false,
                            Foto = "images/categorias/3.png",
                            Nome = "Glitter"
                        },
                        new
                        {
                            Id = (byte)4,
                            Banner = false,
                            Filtrar = true,
                            Foto = "",
                            Nome = "Chaveiros"
                        },
                        new
                        {
                            Id = (byte)5,
                            Banner = false,
                            Filtrar = true,
                            Foto = "",
                            Nome = "Marca-Páginas"
                        },
                        new
                        {
                            Id = (byte)6,
                            Banner = false,
                            Filtrar = true,
                            Foto = "",
                            Nome = "Placa"
                        });
                });

            modelBuilder.Entity("DmResinas.Models.Cor", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CodigoHexa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Cor");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CodigoHexa = "#000000",
                            Nome = "Preto"
                        },
                        new
                        {
                            Id = (byte)2,
                            CodigoHexa = "#efca3e",
                            Nome = "Amarelo"
                        },
                        new
                        {
                            Id = (byte)3,
                            CodigoHexa = "#9399a7",
                            Nome = "Cinza"
                        },
                        new
                        {
                            Id = (byte)4,
                            CodigoHexa = "#85DECB",
                            Nome = "Verde Água"
                        },
                        new
                        {
                            Id = (byte)5,
                            CodigoHexa = "#bd1600",
                            Nome = "Vermelho"
                        },
                        new
                        {
                            Id = (byte)6,
                            CodigoHexa = "#ffffff",
                            Nome = "Branco"
                        },
                        new
                        {
                            Id = (byte)7,
                            CodigoHexa = "#00E0FF",
                            Nome = "Azul Turquesa"
                        },
                        new
                        {
                            Id = (byte)8,
                            CodigoHexa = "#7ab5f9",
                            Nome = "Azul Candy"
                        },
                        new
                        {
                            Id = (byte)9,
                            CodigoHexa = "#D6B563",
                            Nome = "Bege"
                        },
                        new
                        {
                            Id = (byte)10,
                            CodigoHexa = "#efe48a",
                            Nome = "Amarelo Vintage"
                        },
                        new
                        {
                            Id = (byte)11,
                            CodigoHexa = "#978ec5",
                            Nome = "Lilás"
                        },
                        new
                        {
                            Id = (byte)12,
                            CodigoHexa = "#df98b9",
                            Nome = "Rosa Flamingo"
                        },
                        new
                        {
                            Id = (byte)13,
                            CodigoHexa = "#ffffff",
                            Nome = "Branco Perolado"
                        },
                        new
                        {
                            Id = (byte)14,
                            CodigoHexa = "#524f40",
                            Nome = "Cinza Perolado"
                        },
                        new
                        {
                            Id = (byte)15,
                            CodigoHexa = "#20362d",
                            Nome = "Verde Escuro Perolado"
                        },
                        new
                        {
                            Id = (byte)16,
                            CodigoHexa = "#001386",
                            Nome = "Azul Escuro Perolado"
                        },
                        new
                        {
                            Id = (byte)17,
                            CodigoHexa = "#034edb",
                            Nome = "Azul Perolado"
                        },
                        new
                        {
                            Id = (byte)18,
                            CodigoHexa = "#2890e5",
                            Nome = "Azul Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)19,
                            CodigoHexa = "#835426",
                            Nome = "Marrom Escuro Perolado"
                        },
                        new
                        {
                            Id = (byte)20,
                            CodigoHexa = "#5e4624",
                            Nome = "Marrom Perolado"
                        },
                        new
                        {
                            Id = (byte)21,
                            CodigoHexa = "#835426",
                            Nome = "Bronze Perolado"
                        },
                        new
                        {
                            Id = (byte)22,
                            CodigoHexa = "#ac7032",
                            Nome = "Marrom Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)23,
                            CodigoHexa = "#f03b04",
                            Nome = "Laranja Perolado"
                        },
                        new
                        {
                            Id = (byte)24,
                            CodigoHexa = "#e8ce33",
                            Nome = "Amarelo Perolado"
                        },
                        new
                        {
                            Id = (byte)25,
                            CodigoHexa = "#e0a621",
                            Nome = "Dourado Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)26,
                            CodigoHexa = "#cc9900",
                            Nome = "Dourado Perolado"
                        },
                        new
                        {
                            Id = (byte)27,
                            CodigoHexa = "#581598",
                            Nome = "Roxo Perolado"
                        },
                        new
                        {
                            Id = (byte)28,
                            CodigoHexa = "#ffb2d1",
                            Nome = "Rosa Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)29,
                            CodigoHexa = "#e17282",
                            Nome = "Rosa Chiclete Perolado"
                        },
                        new
                        {
                            Id = (byte)30,
                            CodigoHexa = "#cb3038",
                            Nome = "Pink Perolado"
                        },
                        new
                        {
                            Id = (byte)31,
                            CodigoHexa = "#cc2862",
                            Nome = "Rosa Perolado"
                        },
                        new
                        {
                            Id = (byte)32,
                            CodigoHexa = "#f3134f",
                            Nome = "Rosa Choque Perolado"
                        },
                        new
                        {
                            Id = (byte)33,
                            CodigoHexa = "#a31208",
                            Nome = "Cobre Perolado"
                        },
                        new
                        {
                            Id = (byte)34,
                            CodigoHexa = "#4fdb22",
                            Nome = "Verde Fluorescente Perolado"
                        },
                        new
                        {
                            Id = (byte)35,
                            CodigoHexa = "#06785f",
                            Nome = "Verde Esmeralda Perolado"
                        },
                        new
                        {
                            Id = (byte)36,
                            CodigoHexa = "#38ab72",
                            Nome = "Verde Água Perolado"
                        },
                        new
                        {
                            Id = (byte)37,
                            CodigoHexa = "#1d5236",
                            Nome = "Verde Bandeira Perolado"
                        },
                        new
                        {
                            Id = (byte)38,
                            CodigoHexa = "#9dbd69",
                            Nome = "Verde Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)39,
                            CodigoHexa = "#d4124e",
                            Nome = "Magenta Perolado"
                        });
                });

            modelBuilder.Entity("DmResinas.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Descricaoresumida")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dimensao")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Material")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Elegante e refinado, nosso chaveiro de letra A é uma obra-prima artesanal feita com resina de alta qualidade, realçada por uma delicada folha de ouro que confere um toque de sofisticação. A cor é totalmente personalizável, permitindo que você escolha a tonalidade que melhor reflete seu estilo único. Este chaveiro é mais do que um acessório funcional; é uma expressão de sua individualidade, combinando design contemporâneo com um toque de luxo. Leve consigo não apenas suas chaves, mas uma peça exclusiva que reflete seu gosto refinado.",
                            Descricaoresumida = "Chaveiro em formato de Letra A",
                            Destaque = true,
                            Nome = "Letra A com Nome",
                            Peso = 0m,
                            Preco = 20m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Deslumbre-se com a sofisticação do nosso chaveiro exclusivo de letra B, meticulosamente confeccionado em resina de alta qualidade que irradia um brilho sutil. Uma delicada flor adorna a peça, acrescentando um toque de elegância, enquanto um pingente de borboleta simboliza transformação e beleza. A cor personalizável oferece a oportunidade de personalizar esta obra de arte conforme seu estilo e preferências únicas. Este não é apenas um chaveiro, é uma declaração de estilo refinado, perfeito para aqueles que apreciam acessórios distintos e atemporais.",
                            Descricaoresumida = "Chaveiro em formato de Letra B",
                            Destaque = true,
                            Nome = "Letra B com Nome",
                            Peso = 0m,
                            Preco = 20m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Explore a elegância contemporânea com nosso chaveiro exclusivo de letra D, esculpido com maestria em resina de alta qualidade. Intrigantes borboletas douradas adornam a peça, conferindo-lhe um toque de sofisticação e leveza. O efeito de fumaça sutil proporciona uma aura única, elevando a peça a um patamar de distinção. A cor personalizável permite que você dê vida à sua visão estética, transformando este chaveiro em um acessório verdadeiramente único. Uma fusão de design inovador e artesanato excepcional, este chaveiro não apenas organiza suas chaves, mas também acrescenta um toque de requinte ao seu estilo diário.",
                            Descricaoresumida = "Chaveiro em formato de Letra D",
                            Destaque = true,
                            Nome = "Letra D",
                            Peso = 0m,
                            Preco = 20m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Desfrute de momentos de leitura ainda mais refinados com nosso marcador de páginas exclusivo, meticulosamente elaborado em resina de alta qualidade e enriquecido com uma delicada folha de ouro. Este marcador transcende a funcionalidade, elevando-se a uma obra de arte que reflete sua sofisticação pessoal. A cor personalizável oferece a liberdade de harmonizar o marcador com seu estilo único, enquanto a folha de ouro adiciona um toque de luxo discreto. Seja em romances envolventes ou textos profundos, este marcador não só preserva sua página, mas também acrescenta um toque de elegância ao seu momento de leitura. Experimente a fusão sublime de estética refinada e praticidade inigualável.",
                            Descricaoresumida = "Marca Página Elegante",
                            Destaque = true,
                            Nome = "Marca Página Três Cores",
                            Peso = 0m,
                            Preco = 30m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Evoque um toque de glamour em suas leituras com nosso marcador de páginas exclusivo, meticulosamente confeccionado em resina e acentuado por um brilho sutil de glitter. Personalize-o com seu nome, elevando-o de simples acessório a uma peça verdadeiramente única. A cor, à sua escolha, possibilita uma sintonia perfeita com seu estilo pessoal. Este marcador é mais do que uma simples ferramenta funcional; é uma expressão de sua individualidade refinada, combinando design contemporâneo com um toque de sofisticação. Deixe sua marca nas páginas com este acessório que equilibra o brilho discreto com a personalização elegante.",
                            Descricaoresumida = "Marca Página Elegante com Nome",
                            Destaque = true,
                            Nome = "Marca Página com Nome",
                            Peso = 0m,
                            Preco = 30m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Encante-se com a beleza atemporal do nosso marcador de páginas, esculpido em resina com a graciosa forma de uma cauda de sereia. Uma fusão de elegância e fantasia, este marcador acrescenta um toque de sofisticação à sua leitura diária. A cor personalizável permite que você adapte esta peça singular ao seu estilo pessoal, transformando cada momento de pausa na narrativa em uma experiência verdadeiramente cativante. Seja mergulhando em clássicos literários ou navegando por novos horizontes, este marcador de cauda de sereia é um símbolo subtil de sua apreciação pela estética refinada e pela magia da literatura.",
                            Descricaoresumida = "Marca Página Elegante de cauda de sereia",
                            Destaque = true,
                            Nome = "Marca Página Sereia",
                            Peso = 0m,
                            Preco = 30m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Celebre a individualidade com nosso chaveiro exclusivo de letra K, meticulosamente esculpido em resina de alta qualidade, enriquecido com a beleza intemporal de flores delicadamente dispostas. O toque sutil de glitter adiciona uma pitada de sofisticação, elevando este acessório a uma peça única que reflete sua personalidade distinta. A cor personalizável oferece a liberdade de adaptar o chaveiro ao seu estilo pessoal, tornando-o mais do que um simples objeto funcional, mas uma declaração de elegância e originalidade. Seja para organizar suas chaves ou para adornar sua bolsa, este chaveiro é uma expressão encantadora de estilo refinado e apreço pela beleza artística.",
                            Descricaoresumida = "Chaveiro em formato de Letra K",
                            Destaque = true,
                            Nome = "Letra K",
                            Peso = 0m,
                            Preco = 20m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Explore a elegância única com nosso chaveiro exclusivo de letra L, meticulosamente esculpido em resina de alta qualidade e enriquecido com o luxo discreto de uma folha de ouro. Uma flor delicada adiciona um toque de sofisticação, transformando este chaveiro em uma peça de arte funcional. A cor personalizável permite que você adapte este acessório refinado ao seu estilo pessoal, tornando-o mais do que apenas um item utilitário, mas uma expressão distinta de sua individualidade. Seja em suas chaves ou como um adorno refinado, este chaveiro é um testemunho de estilo refinado e apreço pela qualidade artesanal.",
                            Descricaoresumida = "Chaveiro em formato de Letra L",
                            Destaque = true,
                            Nome = "Letra L",
                            Peso = 0m,
                            Preco = 20m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Desperte a sofisticação com nosso chaveiro exclusivo de letra N, uma peça de resina cuidadosamente trabalhada, enriquecida com a sutileza do glitter que confere um brilho discreto. Uma flor delicadamente esculpida adiciona um toque de elegância, transformando este acessório em uma expressão refinada de estilo pessoal. A cor personalizável permite uma adaptação perfeita ao seu gosto distinto, tornando este chaveiro mais do que uma simples utilidade, mas uma declaração de individualidade. Seja em sua bolsa ou organizando suas chaves, este chaveiro é uma fusão harmoniosa de design contemporâneo e toques artísticos, criando um acessório que transcende o ordinário.",
                            Descricaoresumida = "Chaveiro em formato de Letra N",
                            Destaque = true,
                            Nome = "Letra N",
                            Peso = 0m,
                            Preco = 20m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Placa para Manicures tiratem fotos de suas clientes após fazerem a unha para promover a divulgação da profissional.",
                            Descricaoresumida = "Placa para Manicures com Logomarca e nome da profissional",
                            Destaque = true,
                            Nome = "Placa de Manicure com Logotipo",
                            Peso = 0m,
                            Preco = 40m
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Placa para Manicures tiratem fotos de suas clientes após fazerem a unha para promover a divulgação da profissional.",
                            Descricaoresumida = "Placa para Manicures tirarem fotos das unhas",
                            Destaque = true,
                            Nome = "Placa de Manicure com Logotipo",
                            Peso = 0m,
                            Preco = 40m
                        });
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoAvaliacao", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("AvaliacaoData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AvaliacaoTexto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<byte?>("ProdutoNota")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ProdutoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProdutoAvaliacao");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCategoria", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<byte>("CategoriaId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnOrder(2);

                    b.HasKey("ProdutoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProdtoCategoria");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = (byte)4
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = (byte)4
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = (byte)4
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = (byte)5
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = (byte)5
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = (byte)5
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = (byte)4
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = (byte)4
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = (byte)4
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = (byte)6
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = (byte)3
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = (byte)6
                        });
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCor", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<byte>("CorId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnOrder(2);

                    b.HasKey("ProdutoId", "CorId");

                    b.HasIndex("CorId");

                    b.ToTable("ProdutoCor");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CorId = (byte)16
                        },
                        new
                        {
                            ProdutoId = 2,
                            CorId = (byte)27
                        },
                        new
                        {
                            ProdutoId = 3,
                            CorId = (byte)29
                        },
                        new
                        {
                            ProdutoId = 4,
                            CorId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 4,
                            CorId = (byte)5
                        },
                        new
                        {
                            ProdutoId = 5,
                            CorId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 6,
                            CorId = (byte)7
                        },
                        new
                        {
                            ProdutoId = 7,
                            CorId = (byte)35
                        },
                        new
                        {
                            ProdutoId = 8,
                            CorId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 9,
                            CorId = (byte)16
                        },
                        new
                        {
                            ProdutoId = 10,
                            CorId = (byte)32
                        },
                        new
                        {
                            ProdutoId = 11,
                            CorId = (byte)12
                        });
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoFoto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("ArquivoFoto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoFotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProdutoId = 1,
                            ArquivoFoto = "/images/Produtos/1/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 2,
                            ProdutoId = 2,
                            ArquivoFoto = "/images/Produtos/2/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 3,
                            ProdutoId = 3,
                            ArquivoFoto = "/images/Produtos/3/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 4,
                            ProdutoId = 4,
                            ArquivoFoto = "/images/Produtos/9/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 5,
                            ProdutoId = 5,
                            ArquivoFoto = "/images/Produtos/10/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 6,
                            ProdutoId = 6,
                            ArquivoFoto = "/images/Produtos/11/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 7,
                            ProdutoId = 7,
                            ArquivoFoto = "/images/Produtos/4/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 8,
                            ProdutoId = 8,
                            ArquivoFoto = "/images/Produtos/5/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 9,
                            ProdutoId = 9,
                            ArquivoFoto = "/images/Produtos/6/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 10,
                            ProdutoId = 10,
                            ArquivoFoto = "/images/Produtos/7/1.png",
                            Destaque = true
                        },
                        new
                        {
                            Id = 11,
                            ProdutoId = 11,
                            ArquivoFoto = "/images/Produtos/8/1.png",
                            Destaque = true
                        });
                });

            modelBuilder.Entity("DmResinas.Models.Tamanho", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Tamanho");
                });

            modelBuilder.Entity("DmResinas.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = "66ab7735-dfc0-49bb-9379-02c7ff3cc738",
                            DataNascimento = new DateTime(2006, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Foto = "/img/users/avatar.png",
                            Nome = "Bard0u"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "869d3187-0ff2-4880-9d27-c22da1ec1619",
                            ConcurrencyStamp = "f74f0355-6414-468e-ac3e-a405b5084404",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "330a0642-f381-47eb-bc76-d5b5a4e20c37",
                            ConcurrencyStamp = "2d2bd2d7-1b92-4e97-8edf-ab02bce0fe98",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONARIO"
                        },
                        new
                        {
                            Id = "71d01fef-da3d-4140-8bb7-01651ce361e3",
                            ConcurrencyStamp = "53c87255-0979-4197-a4c4-25c8359d0e66",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "66ab7735-dfc0-49bb-9379-02c7ff3cc738",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2778597a-bd73-41b1-a743-67cd055f13a7",
                            Email = "admin@dmresinas.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DMRESINAS.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJzO2VQeUvyuNHUgxoCbbN+MizjrH0JRuoudx1ia4HLs2i0kjxjngRCDgVZWN4BiGQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8bbda3a9-3456-458c-9d71-3488333d752b",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "66ab7735-dfc0-49bb-9379-02c7ff3cc738",
                            RoleId = "869d3187-0ff2-4880-9d27-c22da1ec1619"
                        },
                        new
                        {
                            UserId = "66ab7735-dfc0-49bb-9379-02c7ff3cc738",
                            RoleId = "330a0642-f381-47eb-bc76-d5b5a4e20c37"
                        },
                        new
                        {
                            UserId = "66ab7735-dfc0-49bb-9379-02c7ff3cc738",
                            RoleId = "71d01fef-da3d-4140-8bb7-01651ce361e3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DmResinas.Models.Categoria", b =>
                {
                    b.HasOne("DmResinas.Models.Categoria", "CategoriaPai")
                        .WithMany()
                        .HasForeignKey("CategoriaPaiId");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoAvaliacao", b =>
                {
                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmResinas.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCategoria", b =>
                {
                    b.HasOne("DmResinas.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Categorias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCor", b =>
                {
                    b.HasOne("DmResinas.Models.Cor", "Cor")
                        .WithMany("Produtos")
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Cores")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoFoto", b =>
                {
                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DmResinas.Models.Usuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "AccountUser")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DmResinas.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("DmResinas.Models.Cor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("DmResinas.Models.Produto", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Categorias");

                    b.Navigation("Cores");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("DmResinas.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
