// <auto-generated />
using System;
using DmResinas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DmResinas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DmResinas.Models.Categoria", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Banner")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("CategoriaPaiId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Filtrar")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Banner = true,
                            Filtrar = true,
                            Foto = "images/categorias/1.jpg",
                            Nome = "Folha de Ouro"
                        },
                        new
                        {
                            Id = (byte)2,
                            Banner = true,
                            Filtrar = true,
                            Foto = "images/categorias/2.jpg",
                            Nome = "Flores"
                        },
                        new
                        {
                            Id = (byte)3,
                            Banner = true,
                            Filtrar = false,
                            Foto = "images/categorias/3.jpg",
                            Nome = "Decoração"
                        },
                        new
                        {
                            Id = (byte)4,
                            Banner = false,
                            CategoriaPaiId = (byte)3,
                            Filtrar = true,
                            Foto = "",
                            Nome = "Chaveiros"
                        },
                        new
                        {
                            Id = (byte)5,
                            Banner = false,
                            CategoriaPaiId = (byte)3,
                            Filtrar = true,
                            Foto = "",
                            Nome = "Marca Páginas"
                        },
                        new
                        {
                            Id = (byte)6,
                            Banner = false,
                            CategoriaPaiId = (byte)3,
                            Filtrar = true,
                            Foto = "",
                            Nome = "Placa"
                        });
                });

            modelBuilder.Entity("DmResinas.Models.Cor", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CodigoHexa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Cor");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CodigoHexa = "#000000",
                            Nome = "Preto"
                        },
                        new
                        {
                            Id = (byte)2,
                            CodigoHexa = "#efca3e",
                            Nome = "Amarelo"
                        },
                        new
                        {
                            Id = (byte)3,
                            CodigoHexa = "#9399a7",
                            Nome = "Cinza"
                        },
                        new
                        {
                            Id = (byte)4,
                            CodigoHexa = "#85dedc",
                            Nome = "Verde Água"
                        },
                        new
                        {
                            Id = (byte)5,
                            CodigoHexa = "#bd1600",
                            Nome = "Vermelho"
                        },
                        new
                        {
                            Id = (byte)6,
                            CodigoHexa = "#ffffff",
                            Nome = "Branco"
                        },
                        new
                        {
                            Id = (byte)7,
                            CodigoHexa = "#1b4a82",
                            Nome = "Azul Turquesa"
                        },
                        new
                        {
                            Id = (byte)8,
                            CodigoHexa = "#7ab5f9",
                            Nome = "Azul Candy"
                        },
                        new
                        {
                            Id = (byte)9,
                            CodigoHexa = "#7ab5f9",
                            Nome = "Bege"
                        },
                        new
                        {
                            Id = (byte)10,
                            CodigoHexa = "#efe48a",
                            Nome = "Amarelo Vintage"
                        },
                        new
                        {
                            Id = (byte)11,
                            CodigoHexa = "#978ec5",
                            Nome = "Lilás"
                        },
                        new
                        {
                            Id = (byte)12,
                            CodigoHexa = "#df98b9",
                            Nome = "Rosa Flamingo"
                        },
                        new
                        {
                            Id = (byte)13,
                            CodigoHexa = "#ffffff",
                            Nome = "Branco Perolado"
                        },
                        new
                        {
                            Id = (byte)14,
                            CodigoHexa = "#524f40",
                            Nome = "Cinza Perolado"
                        },
                        new
                        {
                            Id = (byte)15,
                            CodigoHexa = "#20362d",
                            Nome = "Verde Escuro Perolado"
                        },
                        new
                        {
                            Id = (byte)16,
                            CodigoHexa = "#001386",
                            Nome = "Azul Escuro Perolado"
                        },
                        new
                        {
                            Id = (byte)17,
                            CodigoHexa = "#034edb",
                            Nome = "Azul Perolado"
                        },
                        new
                        {
                            Id = (byte)18,
                            CodigoHexa = "#2890e5",
                            Nome = "Azul Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)19,
                            CodigoHexa = "#835426",
                            Nome = "Marrom Escuro Perolado"
                        },
                        new
                        {
                            Id = (byte)20,
                            CodigoHexa = "#5e4624",
                            Nome = "Marrom Perolado"
                        },
                        new
                        {
                            Id = (byte)21,
                            CodigoHexa = "#835426",
                            Nome = "Bronze Perolado"
                        },
                        new
                        {
                            Id = (byte)22,
                            CodigoHexa = "#ac7032",
                            Nome = "Marrom Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)23,
                            CodigoHexa = "#f03b04",
                            Nome = "Laranja Perolado"
                        },
                        new
                        {
                            Id = (byte)24,
                            CodigoHexa = "#e8ce33",
                            Nome = "Amarelo Perolado"
                        },
                        new
                        {
                            Id = (byte)25,
                            CodigoHexa = "#e0a621",
                            Nome = "Dourado Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)26,
                            CodigoHexa = "#cc9900",
                            Nome = "Dourado Perolado"
                        },
                        new
                        {
                            Id = (byte)27,
                            CodigoHexa = "#581598",
                            Nome = "Roxo Perolado"
                        },
                        new
                        {
                            Id = (byte)28,
                            CodigoHexa = "#ffb2d1",
                            Nome = "Rosa Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)29,
                            CodigoHexa = "#e17282",
                            Nome = "Rosa Chiclete Perolado"
                        },
                        new
                        {
                            Id = (byte)30,
                            CodigoHexa = "#cb3038",
                            Nome = "Pink Perolado"
                        },
                        new
                        {
                            Id = (byte)31,
                            CodigoHexa = "#cc2862",
                            Nome = "Rosa Perolado"
                        },
                        new
                        {
                            Id = (byte)32,
                            CodigoHexa = "#f3134f",
                            Nome = "Rosa Choque Perolado"
                        },
                        new
                        {
                            Id = (byte)33,
                            CodigoHexa = "#a31208",
                            Nome = "Cobre Perolado"
                        },
                        new
                        {
                            Id = (byte)34,
                            CodigoHexa = "#4fdb22",
                            Nome = "Verde Fluorescente Perolado"
                        },
                        new
                        {
                            Id = (byte)35,
                            CodigoHexa = "#06785f",
                            Nome = "Verde Esmeralda Perolado"
                        },
                        new
                        {
                            Id = (byte)36,
                            CodigoHexa = "#38ab72",
                            Nome = "Verde Água Perolado"
                        },
                        new
                        {
                            Id = (byte)37,
                            CodigoHexa = "#1d5236",
                            Nome = "Verde Bandeira Perolado"
                        },
                        new
                        {
                            Id = (byte)38,
                            CodigoHexa = "#9dbd69",
                            Nome = "Verde Claro Perolado"
                        },
                        new
                        {
                            Id = (byte)39,
                            CodigoHexa = "#d4124e",
                            Nome = "Magenta Perolado"
                        });
                });

            modelBuilder.Entity("DmResinas.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("Descricaoresumida")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Dimensao")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Material")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Letra L",
                            Peso = 0m,
                            Preco = 20.64m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Letra J",
                            Peso = 0m,
                            Preco = 35.31m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Letra K",
                            Peso = 0m,
                            Preco = 25.50m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Marca Página",
                            Peso = 0m,
                            Preco = 75.25m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Marca Página",
                            Peso = 0m,
                            Preco = 53.0m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Marca Página",
                            Peso = 0m,
                            Preco = 25.85m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Letra A",
                            Peso = 0m,
                            Preco = 63.16m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Letra B",
                            Peso = 0m,
                            Preco = 18.49m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Letra D",
                            Peso = 0m,
                            Preco = 93.20m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Placa Manicure",
                            Peso = 0m,
                            Preco = 75.0m
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Aenean sit amet gravida nisi. Nam fermentum est felis, quis feugiat nunc fringilla sit amet. Ut in blandit ipsum. Quisque luctus dui at ante aliquet, in hendrerit lectus interdum. Morbi elementum sapien rhoncus pretium maximus. Nulla lectus enim, cursus et elementum sed, sodales vitae eros. Ut ex quam, porta consequat interdum in, faucibus eu velit. Quisque rhoncus ex ac libero varius molestie. Aenean tempor sit amet orci nec iaculis. Cras sit amet nulla libero. Curabitur dignissim, nunc nec laoreet consequat, purus nunc porta lacus, vel efficitur tellus augue in ipsum. Cras in arcu sed metus rutrum iaculis. Nulla non tempor erat. Duis in egestas nunc.",
                            Descricaoresumida = "Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat",
                            Destaque = true,
                            Nome = "Placa Manicure",
                            Peso = 0m,
                            Preco = 63.15m
                        });
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoAvaliacao", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("AvaliacaoData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AvaliacaoTexto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<byte?>("ProdutoNota")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ProdutoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProdutoAvaliacao");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCategoria", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<byte>("CategoriaId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnOrder(2);

                    b.HasKey("ProdutoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProdtoCategoria");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = (byte)2
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = (byte)1
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = (byte)6
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = (byte)5
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = (byte)3
                        });
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCor", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<byte>("CorId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnOrder(2);

                    b.HasKey("ProdutoId", "CorId");

                    b.HasIndex("CorId");

                    b.ToTable("ProdutoCor");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoFoto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("ArquivoFoto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoFotos");
                });

            modelBuilder.Entity("DmResinas.Models.Tamanho", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Tamanho");
                });

            modelBuilder.Entity("DmResinas.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = "86dbd1e2-28ee-400f-8915-bbeb5a58e321",
                            DataNascimento = new DateTime(2006, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Foto = "/img/users/avatar.png",
                            Nome = "Bard0u"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "be4fed93-b887-49c5-a786-8bfdf8fa1c54",
                            ConcurrencyStamp = "aec03673-6e4e-476a-aedc-14b5448eeee7",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "9649b275-801e-468d-ab3b-a5a5668102ea",
                            ConcurrencyStamp = "2156eb15-2102-4542-8d04-cda7c8d9e664",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONARIO"
                        },
                        new
                        {
                            Id = "4931f139-d83c-47d9-a66a-afa60fc40bf5",
                            ConcurrencyStamp = "75fce8f9-9b6a-4f41-8b96-aaed609bd66c",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "86dbd1e2-28ee-400f-8915-bbeb5a58e321",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1ddeafa-3bcb-4ea6-977a-ee41be6e5f0d",
                            Email = "admin@dmresinas.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DMRESINAS.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ0RJ42iepS/C1JNg5zCd07IIxuzJhZtlJjVredic4Y/9EZ5W1VnFi+7PSBJqzumeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "732b3a56-69c2-4fa1-8533-e9dce2565867",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "86dbd1e2-28ee-400f-8915-bbeb5a58e321",
                            RoleId = "be4fed93-b887-49c5-a786-8bfdf8fa1c54"
                        },
                        new
                        {
                            UserId = "86dbd1e2-28ee-400f-8915-bbeb5a58e321",
                            RoleId = "9649b275-801e-468d-ab3b-a5a5668102ea"
                        },
                        new
                        {
                            UserId = "86dbd1e2-28ee-400f-8915-bbeb5a58e321",
                            RoleId = "4931f139-d83c-47d9-a66a-afa60fc40bf5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DmResinas.Models.Categoria", b =>
                {
                    b.HasOne("DmResinas.Models.Categoria", "CategoriaPai")
                        .WithMany()
                        .HasForeignKey("CategoriaPaiId");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoAvaliacao", b =>
                {
                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmResinas.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCategoria", b =>
                {
                    b.HasOne("DmResinas.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Categorias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoCor", b =>
                {
                    b.HasOne("DmResinas.Models.Cor", "Cor")
                        .WithMany("Produtos")
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Cores")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DmResinas.Models.ProdutoFoto", b =>
                {
                    b.HasOne("DmResinas.Models.Produto", "Produto")
                        .WithMany("Fotos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DmResinas.Models.Usuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "AccountUser")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DmResinas.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("DmResinas.Models.Cor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("DmResinas.Models.Produto", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Categorias");

                    b.Navigation("Cores");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("DmResinas.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
